# Generated by Django 4.0.5 on 2022-06-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgProcess', '0003_uploadphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphotos',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
