# Generated by Django 2.2.5 on 2022-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgProcess', '0009_auto_20220712_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelphotos2',
            name='labelstatus',
            field=models.BooleanField(),
        ),
    ]
