# Generated by Django 2.2.5 on 2022-08-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgProcess', '0010_auto_20220712_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
