# Generated by Django 2.2.5 on 2022-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgProcess', '0011_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfusePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
