apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIubGR2LmVpLnR1bS5kZTo1MDA1Ijp7InVzZXJuYW1lIjoiZ2U5NnpldCIsInBhc3N3b3JkIjoiSHpjMTI0MTcxZGUiLCJlbWFpbCI6ImdlOTZ6ZXRAbXl0dW0uZGUiLCJhdXRoIjoiWjJVNU5ucGxkRHBJZW1NeE1qUXhOekZrWlE9PSJ9fX0=
kind: Secret
metadata:
  name: imgcred-group06
  namespace: group06
type: kubernetes.io/dockerconfigjson