apiVersion: v1
kind: Service
metadata:
  name: service-group06
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP 
      port: 8888
      targetPort: 8888
      nodePort: 30625