---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIubGR2LmVpLnR1bS5kZTo1MDA1Ijp7InVzZXJuYW1lIjoiZ2U5NnpldCIsInBhc3N3b3JkIjoiSHpjMTI0MTcxZGUiLCJlbWFpbCI6ImdlOTZ6ZXRAbXl0dW0uZGUiLCJhdXRoIjoiWjJVNU5ucGxkRHBJZW1NeE1qUXhOekZrWlE9PSJ9fX0=
kind: Secret
metadata:
  name: imgcred-group06
  namespace: group06
type: kubernetes.io/dockerconfigjson

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-group06
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: gitlab.ldv.ei.tum.de:5005/ami2022/group06
          name: container-group06
          ports:
            - containerPort: 8888
      imagePullSecrets:
        - name: imgcred-group06

---

apiVersion: v1
kind: Service
metadata:
  name: service-group06
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP 
      port: 8888
      targetPort: 8888
      nodePort: 30625