apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-smb-group06
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: group06pv-skjefhe  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//10.195.8.70/group06"
    nodeStageSecretRef:
      name: smbcreds-group06
      namespace: group06
